### ISSUE TITLE
Add structr/meetdown

### ISSUE THREAD

**Issue by coderbyheart** [coderbyheart/open-source-meetup-alternatives#8]
https://github.com/structr/meetdown

**Comment by bkil** [comment]
I see the last update of the meetdown repository is from 2019-11-04. The demo site has a https certificate error.

Should we perhaps add a paragraph to split the list to "maintained" and "discontinued" alternatives separately? Discontinued projects could still have valuable code and someone may eventually pick them up as well.

**Comment by coderbyheart** [comment]
I think _in development_ is a good classification for such a project, or _inactive_ if it's a project which hasn't seen commits in 2+ years.
